# Generated by Django 5.0 on 2023-12-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_screens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screens',
            new_name='Screen',
        ),
    ]
