# Generated by Django 5.0 on 2023-12-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_screens_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='status',
            field=models.BooleanField(default='false'),
        ),
    ]
