# Generated by Django 5.0 on 2023-12-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_screen_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='status',
            new_name='active',
        ),
    ]
