# Generated by Django 5.0 on 2023-12-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_status_screen_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.ImageField(upload_to='cards'),
        ),
    ]
