# Generated by Django 5.0 on 2023-12-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.screen')),
            ],
        ),
    ]
