# Generated by Django 5.0 on 2024-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='econtact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='users',
            name='password_retype',
            field=models.CharField(default='email', max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Screen_Room',
        ),
    ]
